#!/usr/bin/env python3
"""Build adaptive trace-construction artifacts for RegTrace domains."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from regtrace_framework.domain_probe import build_all_specs
from regtrace_framework.schema import TraceSpec


def fmt_score(value: float) -> str:
    return f"{value:.2f}"


def write_json(path: Path, spec: TraceSpec) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        json.dump(spec.to_dict(), f, indent=2, sort_keys=True)
        f.write("\n")


def write_markdown(path: Path, specs: list[TraceSpec]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.extend(
        [
            "# Adaptive RegTrace Construction Report",
            "",
            "This report is generated by the executable RegTrace construction probe. "
            "It treats dataset construction as a framework decision rather than as a "
            "manual pre-processing step.",
            "",
            "## Recursive Construction Loop",
            "",
            "1. Inspect available fields and infer review-trace roles.",
            "2. Map local fields into request, response, evidence, label, feedback, and external-corroboration roles.",
            "3. Score whether the corpus has enough observability, evidence, label viability, feedback richness, release viability, and optimization suitability.",
            "4. If the score is weak, reshape the task rather than forcing the SEC schema.",
            "5. Emit a frozen TraceSpec that downstream reviewers and optimizers must obey.",
            "",
            "## Domain Utility Table",
            "",
            "| Domain | Decision | N | Mean | Roles | Evidence | Label | Feedback | External | Release | Optimizer |",
            "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    for spec in specs:
        u = spec.utility
        lines.append(
            "| "
            + " | ".join(
                [
                    spec.domain,
                    spec.decision,
                    str(spec.instance_count),
                    fmt_score(u.mean),
                    fmt_score(u.role_observability),
                    fmt_score(u.evidence_availability),
                    fmt_score(u.label_viability),
                    fmt_score(u.feedback_richness),
                    fmt_score(u.external_corroboration),
                    fmt_score(u.release_viability),
                    fmt_score(u.optimization_suitability),
                ]
            )
            + " |"
        )

    for spec in specs:
        lines.extend(
            [
                "",
                f"## {spec.domain}",
                "",
                f"- Task: {spec.task_name}",
                f"- Decision: `{spec.decision}`",
                f"- Instances: {spec.instance_count}",
                f"- Mean utility: {spec.utility.mean:.2f} / 5",
                "",
                "### Role Mapping",
                "",
                f"- Request: {', '.join(spec.role_mapping.request) or 'none'}",
                f"- Response: {', '.join(spec.role_mapping.response) or 'none'}",
                f"- Evidence: {', '.join(spec.role_mapping.evidence) or 'none'}",
                f"- Label: {', '.join(spec.role_mapping.label) or 'none'}",
                f"- Feedback: {', '.join(spec.role_mapping.feedback) or 'none'}",
                f"- External corroboration: {', '.join(spec.role_mapping.external_corroboration) or 'none'}",
                "",
                "### Label Policy",
                "",
                spec.label_definition,
                "",
                "### Feedback Policy",
                "",
                f"- Scalar: {spec.feedback_policy.scalar}",
                f"- Category: {spec.feedback_policy.category or 'none'}",
                f"- Full text: {spec.feedback_policy.full_text or 'none'}",
                f"- External text: {spec.feedback_policy.external_text or 'none'}",
                f"- Forbidden at test time: {', '.join(spec.feedback_policy.forbidden_test_time_fields) or 'none'}",
                "",
                "### Distributions",
                "",
                f"- Labels: `{json.dumps(spec.label_distribution, ensure_ascii=False)}`",
                f"- Categories: `{json.dumps(spec.category_distribution, ensure_ascii=False)}`",
                "",
                "### Strengths",
                "",
            ]
        )
        lines.extend(f"- {item}" for item in spec.strengths)
        lines.extend(["", "### Risks", ""])
        lines.extend(f"- {item}" for item in spec.risks)
        lines.extend(["", "### Next Action", "", spec.next_action])

    lines.extend(
        [
            "",
            "## Paper Implication",
            "",
            "The strongest claim is not that one SEC prompt transfers everywhere. "
            "The stronger claim is that RegTrace supplies a reusable construction interface: "
            "for each domain, it decides what counts as request, response, evidence, label, "
            "feedback, and external corroboration, then trains or reshapes the reviewer accordingly. "
            "SEC is the primary benchmark, CMS is a positive cross-regulatory adaptation, and FDA is "
            "a stress test showing that the framework can reshape a corpus when a direct response "
            "channel is not publicly observable.",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--out-dir", type=Path, default=Path("outputs/adaptive_trace_framework"))
    args = parser.parse_args()

    root = args.root.resolve()
    specs = build_all_specs(root)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    for spec in specs:
        slug = (
            spec.domain.lower()
            .replace(" ", "_")
            .replace("-", "_")
            .replace("/", "_")
        )
        write_json(args.out_dir / f"{slug}.trace_spec.json", spec)

    write_markdown(
        root / "docs/review_response/adaptive_trace_framework_report.md",
        specs,
    )
    print(f"Wrote {len(specs)} TraceSpecs to {args.out_dir}")
    print("Wrote docs/review_response/adaptive_trace_framework_report.md")


if __name__ == "__main__":
    main()
